sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 10061
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8gfMgdzotAm5KtCcCA
    access-key-secret: eWK23M5AvOJ5ILgqoc4Yz6cqyXxLw7
    bucket-name: web-tlias-02cys
  redis:
    host: localhost
    port: 6379
